SET SCHEMA FN71168 @
-----------------------------------------
-- TRIGER ZA CENA NA TICKET PRI INSERT
----------------------------------------

CREATE TRIGGER TICKET_TRIGER_ALL_IN
	AFTER INSERT ON TICKET
	REFERENCING NEW AS N 
	FOR EACH ROW MODE DB2SQL
	BEGIN ATOMIC 
	
		CALL FN71168.CATEGORY(N.TRAIN_REF);
		CALL FN71168.TICKET_PRICE(N.ROUTE_REF, N.CLASS_REF, N.ID_CARD, N.RESERVED_SEAT, N.TICKET_ID, N.TRAIN_CATEGORY);
		
	END @

--DROP TRIGGER TICKET_TRIGER_ALL_IN @



------------------------------------------------------------
-- TRIGER PRI INSERT V TABLICA CARDS ZA SMQTANE NA RED_VALUE
------------------------------------------------------------

CREATE TRIGGER REDUNDANCY_VALUE_TRIGGER
	AFTER INSERT ON CARDS
	REFERENCING NEW AS N
	FOR EACH ROW MODE DB2SQL
	BEGIN ATOMIC
		CALL FN71168.CARD_RED_VALUE(N.ID_AB_REF, N.ID_ZL_REF);
	END @
	
--DROP TRIGGER REDUNDANCY_VALUE_TRIGGER @




	
--DROP TRIGGER CATEGORY_ALL_IN @
-------------------------------------------------------	
-- TRIGER ZA TABLICA ROUTE ZA PRESMQTANE NA DISTANCIQTA 
-- POSREDSTWOM PODMARSHRUTITE 
------------------------------------------------------
CREATE TRIGGER ROUTE_DISTANCE_TRIGGER 
	AFTER INSERT ON ROUTE
	REFERENCING NEW AS N
	FOR EACH ROW MODE DB2SQL
	BEGIN ATOMIC 
		CALL FN71168.DISTANCE_CALC(N.ROUTE_ID);
	END @
	
--DROP TRIGGER ROUTE_DISTANCE_TRIGGER @



----------------------------------------------------
-- TRIGER ZA TABLICA TICKET ZA POSTAVQNE NA CATEGORIQ 
----------------------------------------------------

--CREATE TRIGGER CATEGORY_ALL_IN
--	AFTER INSERT ON TICKET
---	REFERENCING NEW AS N 
--	FOR EACH ROW MODE DB2SQL
--	BEGIN ATOMIC 
--		CALL FN71168.CATEGORY(N.TRAIN_REF);
--	END @

---------------------------------------	
-- TRIGER ZA CENA NA TICKET PRI UPDATE
--------------------------------------

--CREATE TRIGGER TICKET_TRIGER_ALL_UP 
--	AFTER UPDATE ON TICKET
--	REFERENCING NEW AS N 
--	FOR EACH ROW MODE DB2SQL
--	BEGIN ATOMIC 
--		CALL FN71168.TICKET_PRICE(N.ROUTE_REF, N.CLASS_REF, N.ID_CARD, N.RESERVED_SEAT, TICKET_ID);
--	END @

--DROP TRIGGER TICKET_TRIGER_ALL_UP @