set schema fn71168;


CREATE TABLE STATION
(
STATION_ID CHAR(5) NOT NULL PRIMARY KEY,
NAME VARCHAR(40) UNIQUE NOT NULL,
SITUATION VARCHAR(80) NOT NULL UNIQUE,
PHONE VARCHAR(20) NOT NULL UNIQUE,
TRACKS INTEGER DEFAULT 1 CONSTRAINT TRACKS_CHECK CHECK ( TRACKS >=1),
DEPOT CHAR(1) DEFAULT 'N' CONSTRAINT DEPOT_CHECK CHECK (DEPOT IN('Y','N'))
);

CREATE TABLE DEPOT
(
DEPOT_ID CHAR(3) PRIMARY KEY NOT NULL,
DEPOT_N VARCHAR(40) CONSTRAINT NAME_REF REFERENCES STATION(NAME) ON DELETE SET NULL,
ADDRESS VARCHAR(80) CONSTRAINT ADDRESS_REF REFERENCES STATION(SITUATION) ON DELETE SET NULL
);


CREATE TABLE TRAIN
(
TRAIN_ID CHAR(4) PRIMARY KEY NOT NULL,
TRAIN_NAME VARCHAR(15),
TRAIN_TYPE VARCHAR(15) NOT NULL 
CHECK (TRAIN_TYPE IN ('PASSANGERS','FREIGHT')),
CAPACITY DECIMAL(8,2),
ACTIVITY CHAR(1) DEFAULT 'Y' CONSTRAINT ACTIVITY_CHECK CHECK (ACTIVITY IN ('Y','N')),
TRAIN_CATEGORY VARCHAR(20) CONSTRAINT TRAIN_CATEGORY_CHECK 
CHECK (TRAIN_CATEGORY IN ('FAST', 'EXPRESS', 'ORDINARY')),
DEPOT CHAR(3) CONSTRAINT DEPOT_REF REFERENCES DEPOT(DEPOT_ID) ON DELETE SET NULL
);

CREATE TABLE SEATS
(
SEAT_NUM_1 INTEGER CONSTRAINT SEAT_NUM_1_CHECK CHECK(SEAT_NUM_1 >= 0),
SEAT_NUM_2 INTEGER CONSTRAINT SEAT_NUM_2_CHECK CHECK(SEAT_NUM_2 >= 0),
SEAT_NUM_2_HALL INTEGER CONSTRAINT SEAT_NUM_2_HALL_CHECK CHECK(SEAT_NUM_2_HALL >= 0),
VAN_NUM INTEGER DEFAULT 0 CONSTRAINT VAN_NUM_CHECK CHECK(VAN_NUM >= 0),
BEDS_NUM INTEGER CONSTRAINT BEDS_NUM_CHECK CHECK(BEDS_NUM >= 0),
WAGGON_COUCH_NUM INTEGER CONSTRAINT COUCH_NUM_CHECK CHECK(WAGGON_COUCH_NUM >= 0),
WAGGON_REST_NUM INTEGER CONSTRAINT REST_NUM_CHECK CHECK(WAGGON_REST_NUM >= 0),
TRAIN_REF CHAR(4) CONSTRAINT SEATS_TRAIN_REF REFERENCES TRAIN(TRAIN_ID)
);


CREATE TABLE ROUTE
(
ROUTE_ID CHAR(6) PRIMARY KEY NOT NULL,
STATION_FROM CHAR(5) CONSTRAINT ROUTE_STATION_FROM_REF REFERENCES STATION(STATION_ID) ON DELETE SET NULL,
STATION_TO CHAR(5) CONSTRAINT ROUTE_STATION_TO_REF REFERENCES STATION(STATION_ID) ON DELETE SET NULL,
DISTANCE DECIMAL(8,2) DEFAULT 1 CONSTRAINT DISTANCE_CHECK CHECK (DISTANCE>0)
);


CREATE TABLE SUB_ROUTE
(
SUB_ROUTE_ID CHAR(6),
ROUTE_PID CHAR(6) CONSTRAINT ROUTE_PID_REF REFERENCES ROUTE(ROUTE_ID) ON DELETE SET NULL,
STATION_FROM CHAR(5) CONSTRAINT STATION_FROM_REF REFERENCES STATION(STATION_ID) ON DELETE SET NULL,
STATION_TO CHAR(5) CONSTRAINT STATION_TO_REF REFERENCES STATION(STATION_ID) ON DELETE SET NULL,
DISTANCE DECIMAL(8,2) CONSTRAINT SUBDISTANCE_CHECK CHECK (DISTANCE>0)
);



CREATE TABLE CLASS 
(
CLASS_TYPE VARCHAR(20) PRIMARY KEY NOT NULL CONSTRAINT CLASS_TYPE_CHECK
CHECK(CLASS_TYPE IN ('CLASS 1', 'CLASS 2', 'CLASS 2 HALL', 'BEDROOM', 'COUCH', 'VAN')),
CLASS_VALUE DECIMAL(8,2) DEFAULT 1 CONSTRAINT CLASS_VALUE_CHECK CHECK (CLASS_VALUE >= 0 )
);

CREATE TABLE TIME_TABLE
(
ROUTE_REF CHAR(6) CONSTRAINT TT_ROUTE_REF REFERENCES ROUTE(ROUTE_ID) ON DELETE SET NULL,
TRAIN_REF CHAR(4) CONSTRAINT TT_TRAIN_REF REFERENCES TRAIN(TRAIN_ID) ON DELETE SET NULL,
DEPARTURE_TIME TIME,
ARRIVING_TIME TIME,
DURATION TIME,
TYPE_TT VARCHAR(6) CONSTRAINT TYPE_TT_CHECK CHECK (TYPE_TT IN ('WINTER','SUMMER'))
);

CREATE TABLE PASSENGER 
(
NAME VARCHAR(15) NOT NULL,
FAMILY_NAME VARCHAR(20) NOT NULL,
ADDRESS VARCHAR(40), 
PHONE VARCHAR(20),
EGN CHAR(10) PRIMARY KEY NOT NULL,
STATUS VARCHAR(20) CONSTRAINT STATUS_CHECK CHECK (STATUS IN ('KID', 'STUDENT', 'ADULT', 'YOUNG MAN')),
PLACE VARCHAR(40)
);


CREATE TABLE REDUNDANCY_CARDS
(
RED_CARD CHAR(7) CONSTRAINT RED_CARD_CHECK CHECK (RED_CARD LIKE 'ZL%') PRIMARY KEY NOT NULL,
CARD_TYPE VARCHAR (20) NOT NULL  CONSTRAINT CARD_TYPE1_CHECK
CHECK(CARD_TYPE IN ('KID', 'FAMILY', 'TPL', 'YOUNG MAN', 'CLASSIC', 'STUDENT','ISIC','DSKISICVISAELECTRON','ADULT')),
RED_VALUE DECIMAL(8,2) DEFAULT 1
);


CREATE TABLE SUBS_CARDS
(
SUB_CARD CHAR(7) CONSTRAINT SUB_CARD_CHECK CHECK (SUB_CARD LIKE 'AB%') PRIMARY KEY NOT NULL,
CARD_TYPE VARCHAR (20) NOT NULL  CONSTRAINT CARD_TYPE2_CHECK
CHECK (CARD_TYPE IN ('NORMAL', 'RED 10%')),
RED_VALUE DECIMAL(8,2) DEFAULT 1
);

CREATE TABLE CARDS
(
CARD_ID CHAR(7) NOT NULL PRIMARY KEY CONSTRAINT MAIN_CARD_CHECK CHECK (CARD_ID LIKE ('CD%')),
ID_AB_REF CHAR(7) CONSTRAINT AB_REF REFERENCES SUBS_CARDS(SUB_CARD),
ID_ZL_REF CHAR(7) CONSTRAINT ZL_REF REFERENCES REDUNDANCY_CARDS(RED_CARD),
RED_VALUE DECIMAL(8,2), -- TRIGER 
RELEASE_DATE DATE DEFAULT CURRENT_DATE,
EXPIRE_DATE DATE,
PUB_STATION CHAR(5) REFERENCES STATION(STATION_ID) ON DELETE SET NULL,
EGN_REF CHAR(10) REFERENCES PASSENGER(EGN) ON DELETE SET NULL
);



CREATE TABLE TICKET
(
TICKET_ID CHAR(7) PRIMARY KEY NOT NULL,
SERIES CHAR(7) UNIQUE NOT NULL CONSTRAINT SERIES_CHECK CHECK (SERIES LIKE ('%-%')),
STATION_FROM VARCHAR(40) CONSTRAINT T_STATION_FROM_REF REFERENCES STATION(NAME) ON DELETE SET NULL,
STATION_TO VARCHAR(40) CONSTRAINT T_STATION_TO_REF REFERENCES STATION(NAME) ON DELETE SET NULL,
TRAIN_CATEGORY VARCHAR(20), -- TRIGGER
BOUGHT_FROM CHAR(5) CONSTRAINT BOUGHT_FROM_REF REFERENCES STATION(STATION_ID) ON DELETE SET NULL,
ROUTE_REF CHAR(6) CONSTRAINT T_ROUTE_REF REFERENCES ROUTE(ROUTE_ID) ON DELETE SET NULL,
TRAIN_REF CHAR(4) CONSTRAINT T_TRAIN_REF REFERENCES TRAIN(TRAIN_ID) ON DELETE SET NULL,
TICKET_DATE DATE DEFAULT CURRENT_DATE,
SETOFF_DATE DATE DEFAULT CURRENT_DATE,
RESERVED_SEAT VARCHAR(4) DEFAULT NULL,
PRICE DECIMAL(8,2), -- TRIGGER
INSURANCE_NUM CHAR(8),
ID_CARD CHAR(7) CONSTRAINT CARD_REF REFERENCES CARDS(CARD_ID) ON DELETE SET NULL, -- TRIGER
CLASS_REF VARCHAR(20) CONSTRAINT CLASS_REF REFERENCES CLASS(CLASS_TYPE) ON DELETE SET NULL
);

