SET SCHEMA FN71168;

-----------------------------------------------------------
--INFORMACIQ ZA PYTNICITE SYS SYOTVETNATA KARTA ZA NAMALENIE
------------------------------------------------------------
CREATE VIEW PASSENGER_INFO (FULLNAME, CARD_TYPE, RELEASE_DATE)
AS
SELECT NAME || '   ' || FAMILY_NAME, SUBS_CARDS.CARD_TYPE, CHAR(RELEASE_DATE,EUR) AS RELEASE_DATE
FROM PASSENGER JOIN CARDS ON EGN=EGN_REF 
JOIN SUBS_CARDS ON ID_AB_REF=SUB_CARD
UNION ALL
SELECT NAME || '   ' || FAMILY_NAME AS FULLNAME, REDUNDANCY_CARDS.CARD_TYPE, CHAR(RELEASE_DATE,EUR) AS RELEASE_DATE
FROM PASSENGER JOIN CARDS ON EGN=EGN_REF 
JOIN REDUNDANCY_CARDS ON ID_ZL_REF=RED_CARD;

SELECT *
FROM PASSENGER_INFO;
-------------------------------------------------
--KOLKO BLETA E ZAKUPIL VSEKI 1 OT HORATA S KARTI
-------------------------------------------------
CREATE VIEW BOUGHT_TICKET_FP (FULLNAME, TICKET_NUMBER)
AS
SELECT NAME || '   ' || FAMILY_NAME, COUNT(TICKET_ID)
FROM PASSENGER JOIN CARDS ON EGN=EGN_REF JOIN SUBS_CARDS ON ID_AB_REF=SUB_CARD JOIN TICKET ON CARD_ID=ID_CARD
GROUP BY NAME, FAMILY_NAME
UNION ALL
SELECT NAME || '   ' || FAMILY_NAME AS FULLNAME, COUNT (TICKET_ID)
FROM PASSENGER JOIN CARDS ON EGN=EGN_REF 
JOIN REDUNDANCY_CARDS ON ID_ZL_REF=RED_CARD 
JOIN TICKET ON CARD_ID=ID_CARD
GROUP BY NAME, FAMILY_NAME;

SELECT *
FROM FN71168.BOUGHT_TICKET_FP;
-----------------------------------------------------
-- KOLKO BILETA SA ZAKUPENI I OB6TITE PRIHODI OT TQH
----------------------------------------------------
CREATE VIEW INCOMES(TICKET_NUMBER,INCOME)
AS
SELECT COUNT(TICKET_ID), SUM(PRICE)
FROM TICKET;

SELECT *
FROM FN71168.INCOMES;

--------------------------------------------------------------------------------
--INFORMACIQ VSI4KI VLAKOVE KOITO PRISTIGAT V PLOVDIV PREZ LQTOTO I VOZQT PYTNICI
--------------------------------------------------------------------------------
CREATE VIEW T_AR_PLD(TRAIN_ID, TRAIN_NAME, TRAIN_CATEGORY, ARRIVING_TIME)
AS
SELECT TRAIN_ID, TRAIN_NAME, TRAIN_CATEGORY, ARRIVING_TIME
FROM TRAIN JOIN TIME_TABLE ON TRAIN_ID=TRAIN_REF 
JOIN ROUTE ON ROUTE_ID=ROUTE_REF 
JOIN STATION ON STATION_TO=STATION_ID
WHERE NAME LIKE 'PLOVDIV' AND TYPE_TT LIKE 'SUMMER';

SELECT *
FROM FN71168.T_AR_PLD;

-----------------------------------------------------------------
--DA SE IZVEDAT VSI4KI VLAKOVE KOITO MINAVAT PREZ SEPTEMVRI PREZ 
--ZIMATA PREDI 12 CHASA I SA ZA PLOVDIV
-----------------------------------------------------------------
CREATE VIEW THROUGH_SEPT (STATION_FROM, STRATION_THROUGH, STATION_TO, TRAIN_ID, TRAIN_NAME, TRAIN_CATEGORY)
AS
SELECT ROUTE.STATION_FROM, NAME, ROUTE.STATION_TO, TRAIN_ID, TRAIN_NAME, TRAIN_CATEGORY
FROM TRAIN JOIN TIME_TABLE ON TRAIN_ID=TRAIN_REF 
JOIN ROUTE ON ROUTE_ID=ROUTE_REF 
JOIN SUB_ROUTE ON ROUTE_PID=ROUTE_ID
JOIN STATION ON SUB_ROUTE.STATION_FROM=STATION_ID
WHERE NAME LIKE 'SEPTEMVRI' AND TYPE_TT LIKE 'WINTER'
AND HOUR(DEPARTURE_TIME)< 12 AND ROUTE.STATION_TO='77012';

SELECT *
FROM FN71168.THROUGH_SEPT;
------------------------------------------------------------
--MESTA ZA VTORA KLASA KATO BROIKA VYV VREKI VLAK
------------------------------------------------------------
CREATE VIEW SEATS_SECOND_CL (TRAIN_ID, RESERVED_SEAT_NUM_2)
AS
SELECT DISTINCT TRAIN_ID, COUNT(RESERVED_SEAT)
FROM TICKET JOIN TRAIN ON TRAIN_REF=TRAIN_ID 
JOIN SEATS ON TRAIN_ID=SEATS.TRAIN_REF
WHERE CLASS_REF LIKE 'CLASS 2'
GROUP BY TRAIN_ID;

SELECT *
FROM FN71168.SEATS_SECOND_CL;

--------------------------------------------------------------------------------
--BROQ I TIPA MESTA ZA VSI4KI VLAKOVE, KOITO SA ZA PYTNICI I NQMAT SPALNI VAGONI
-------------------------------------------------------------------------------
CREATE VIEW SEATS_COUNT (TRAIN_ID, CLASS_1, CLASS_2_HALL,WAGGON_REST )
AS
SELECT DISTINCT TRAIN_ID, SEAT_NUM_1, SEAT_NUM_2_HALL, WAGGON_REST_NUM 
FROM TRAIN JOIN SEATS ON TRAIN_ID=TRAIN_REF
WHERE TRAIN_TYPE LIKE 'PASSANGERS' AND BEDS_NUM = 0;

SELECT *
FROM FN71168.SEATS_COUNT;
---------------------------------------------------------------------
--NA KOI DEPA PRINADLEJAT DADENI VLAKOVE
---------------------------------------------------------------------
CREATE VIEW DEPOT_INFO
AS
SELECT DISTINCT TRAIN_ID, DEPOT_N, ADDRESS
FROM DEPOT JOIN TRAIN ON DEPOT_ID=DEPOT;

SELECT *
FROM FN71168.DEPOT_INFO;

---------------------------------------------------------------------------------------------------
--VIDA I BROQ IZDADENI KARTI ZA NAMALENIE I MQSTOTO V KOETO SA IZDADENI I HORATA KOITO GI PRITEJAVAT
----------------------------------------------------------------------------------------------------
CREATE VIEW CARDS_INFO
AS
SELECT CARD_TYPE, COUNT(RED_CARD) AS REDUNDANCY_CARD,NAME AS PUB_STATION
FROM CARDS JOIN REDUNDANCY_CARDS ON ID_ZL_REF=RED_CARD
 JOIN STATION ON STATION_ID=PUB_STATION
GROUP BY CARD_TYPE,NAME
UNION ALL
SELECT CARD_TYPE, COUNT(SUB_CARD) AS SUB_CARD,NAME AS PUB_STATION
FROM CARDS JOIN SUBS_CARDS ON ID_AB_REF=SUB_CARD 
JOIN STATION ON STATION_ID=PUB_STATION
GROUP BY CARD_TYPE,NAME;

SELECT *
FROM FN71168.CARDS_INFO;