set schema fn71168;

DROP TABLE STATION;
DROP TABLE DEPOT;
DROP TABLE TRAIN;
DROP TABLE SEATS;
DROP TABLE ROUTE;
DROP TABLE SUB_ROUTE;
DROP TABLE CLASS;
DROP TABLE TIME_TABLE;
DROP TABLE PASSENGER;
DROP TABLE REDUNDANCY_CARDS;
DROP TABLE SUBS_CARDS;
DROP TABLE CARDS;
DROP TABLE TICKET;
